import { nanoid } from 'nanoid';

export const nearbySpots = [
  {
    id: nanoid(),
    name: 'Praia do tarquinio',
    waveHeight: '2-3',
    windSpeed: '13',
    windDirection: 'SSE',
    rating: 4,
    imageUrl: '/images/a-nearby-spot.png',
    isTopSpot: true,
  },
  {
    id: nanoid(),
    name: 'Praia do tarquinio',
    waveHeight: '2-3',
    windSpeed: '13',
    windDirection: 'SSE',
    rating: 4,
    imageUrl: '/images/a-nearby-spot.png',
    isTopSpot: false,
  },
  {
    id: nanoid(),
    name: 'Praia do tarquinio',
    waveHeight: '2-3',
    windSpeed: '13',
    windDirection: 'SSE',
    rating: 4,
    imageUrl: '/images/a-nearby-spot.png',
    isTopSpot: false,
  },
  {
    id: nanoid(),
    name: 'Praia do tarquinio',
    waveHeight: '2-3',
    windSpeed: '13',
    windDirection: 'SSE',
    rating: 4,
    imageUrl: '/images/a-nearby-spot.png',
    isTopSpot: false,
  },
  {
    id: nanoid(),
    name: 'Praia do tarquinio',
    waveHeight: '2-3',
    windSpeed: '13',
    windDirection: 'SSE',
    rating: 4,
    imageUrl: '/images/a-nearby-spot.png',
    isTopSpot: false,
  },
  {
    id: nanoid(),
    name: 'Praia do tarquinio',
    waveHeight: '2-3',
    windSpeed: '13',
    windDirection: 'SSE',
    rating: 4,
    imageUrl: '/images/a-nearby-spot.png',
    isTopSpot: false,
  },
  {
    id: nanoid(),
    name: 'Praia do tarquinio',
    waveHeight: '2-3',
    windSpeed: '13',
    windDirection: 'SSE',
    rating: 4,
    imageUrl: '/images/a-nearby-spot.png',
    isTopSpot: false,
  },
  {
    id: nanoid(),
    name: 'Praia do tarquinio',
    waveHeight: '2-3',
    windSpeed: '13',
    windDirection: 'SSE',
    rating: 4,
    imageUrl: '/images/a-nearby-spot.png',
    isTopSpot: false,
  },
  {
    id: nanoid(),
    name: 'Praia do tarquinio',
    waveHeight: '2-3',
    windSpeed: '13',
    windDirection: 'SSE',
    rating: 4,
    imageUrl: '/images/a-nearby-spot.png',
    isTopSpot: false,
  },
] as const;

export type NearbySpot = (typeof nearbySpots)[number];
